### ISSUE TITLE
No currency on transactions

### ISSUE THREAD

**Issue by marcossantiago** [jseutter/ofxparse#100]
Hi Guys, 

I have stumble upon some Credit Card statements with international purchases. It contains the tags (CURRATE inside CURRENCY), but the parser doesn't look into those, nor the Transaction objects have those attributes. I will be happy to send a pull request if you point me into the right direction on how to do this.

Ideally, would be nice to have a way to return the converted value, instead of the original one.

**Comment by mralbu** [comment]
I needed to parse CURRENCY tags as well, so I've modified the transaction parser to retrieve transaction currencies other than CURDEF. https://github.com/mralbu/ofxparse/commit/591b6fe4b4e6b16c83ac4fd6c47082889a26fb35
I've added an ofx file to fixtures and a test function for it as well.
Do you think this solution is acceptable? Would you accept it as a pull request?
