### ISSUE TITLE
HELP NEEDED: Build infrastructure

### ISSUE THREAD

**Issue by jseutter** [jseutter/ofxparse#106]
Ofxparse could benefit from having some infrastructure to do things like run tests and create releases.  This issue is for discussing what tools are available and the merits of each.  My own knowledge is not up to date..

**Pretty much needed features:**
1. I would like a tool that gives more immediate feedback to people when they create PRs, as the code is still fresh in their minds.  I would like it to run the tests as well as flake8.
2. The tool should be a service where I don't have to keep a server running.  I have set up servers for this in the past, but keeping them running has been more work than I was willing to commit.

**Some nice to haves, but not critical:**
1. The solution would run on someone else's infrastructure, as maintaining this by myself has been painful to the point where I don't maintain it.
2. Be able to create releases for both python 3 and python 2.7.  This doesn't have to be automatic
3. Generate test coverage stats

What kind of solutions appear to be viable?

**Comment by ajcollett** [comment]
Hello, I think I may have a solution. GitLab has great CI integration, and I'm thinking of setting up a privately hosted machine, or possibly asking my work (Stellenbosch University) to host open source code. Would you be interested in having someone run something like that?

**Comment by nathangrigg** [comment]
travis-ci can do testing and coverage. I think it can do release builds as well

**Comment by jseutter** [comment]
Today I had time to devote to this, and Travis is now running the tests against our PRs.  While I haven't yet found a way to do test coverage stats, simply knowing if the PR breaks the tests is huge.

@ajcollett - I want to thank you for your offer.  There may be other projects with more strenuous testing requirements that would benefit more your proposed solution.  In ofxparse's case, running a complete server just for a PR every few weeks seems like overkill.

@nathangrigg - Thanks for setting up .travis.yml.  You made my day when everything Just Worked. :)
