### ISSUE TITLE
Beautiful Soup 4 no longer supports Python versions < 2.7

### ISSUE THREAD

**Issue by rdsteed** [jseutter/ofxparse#111]
Current releases of Beautiful Soup 4 have dropped support for Python 2.6 and earlier.  Since this is a major dependency, suggest changing ofxparse to match.

**Comment by nathangrigg** [comment]
There is also at least one test ("testThatParseTransactionWithCommaAsDecimalPointAndDotAsSeparator") that uses python 2.7 specific features. 

I'm working on getting a continuous build going, should I drop support for Python 2.6?

**Comment by jseutter** [comment]
Yes, let's drop support for Python 2.6

**Comment by rdsteed** [comment]
This was addressed in PR #121
