### ISSUE TITLE
"Cannot import name OfxParser"

### ISSUE THREAD

**Issue by lowercase00** [jseutter/ofxparse#135]
Anyone else getting this error? Don't know what I might be doing wrong

```
from ofxparse import OfxParser

with codecs.open('~/Desktop/file.ofx') as fileobj:
    ofx = OfxParser.parse(fileobj)
```

**Comment by lowercase00** [comment]
after rebooting my machine I was able to import the module, but started getting an error "no module name codecs". Deleted codecs and it seems to work, will take a better look now, don't know if I'm missing something because of the lack of the codecs.

**Comment by jseutter** [comment]
I think the codecs module is part of the python standard library.  If this is failing, your python environment is likely messed up somehow and unrelated to ofxparse.

Running `python -c 'import codecs'` should complete without errors.
