### ISSUE TITLE
Importing ABC directly from collections module was removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [jseutter/ofxparse#155]
https://bugzilla.redhat.com/show_bug.cgi?id=1792966

https://github.com/jseutter/ofxparse/blob/31f85c74b674e9b5bffe83f618ec7356eb800677/ofxparse/ofxparse.py#L40

Thanks for the library!

**Comment by flamaster2016** [comment]
Thank you!

**Comment by rkhwaja** [comment]
@jseutter Can you make a pypi release with this fix? Python 3.9 will be coming out soon

**Comment by tirkarthi** [comment]
The deprecation removal was deferred to python 3.10 though it was initially merged to python 3.9 due to breakage in libraries.
