### ISSUE TITLE
Time for a new release ?

### ISSUE THREAD

**Issue by Whisno** [jseutter/ofxparse#75]
Hi,
I wish to parse the ledger balance date in production, however this info is extracted from OFX files only since 8331cc7274250880861829c887e859c7ab84e00a (which was committed only 2 months after 0.14 release, such bad luck).

Do you plan a new release anytime soon ?

And thanks for your work on ofxparse, it's very useful.

**Comment by jseutter** [comment]
New release made.  Sorry about the long wait!
