### ISSUE TITLE
README file() example fails in py3

### ISSUE THREAD

**Issue by joeharr4** [jseutter/ofxparse#79]
Since the file() function is gone in Python3, the example in the README doesn't work.  Neither does the obvious substitution of open(), as at least some qfx files have binary characters (i.e., I had to open(file.qfx, 'rb'), and then it worked).  In general, the README could use some work so that it can be understood by non-expert programmers.  I may take a crack at it and offer a pull later, but I wanted to get this in now, in case someone had already done it and hadn't done a pull.

--jh--

**Comment by dorfsmay** [comment]
If there is a need for opening binary file, then the Readme should change to `ofx = OfxParser.parse(open('/tmp/x.ofx', 'rb'))`, since that will work in both python2 and python3.
