### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by egh** [jseutter/ofxparse#97]
Hi,

The latest released version of ofxparse is 0.14 (https://pypi.python.org/pypi/ofxparse), from 2013.

The latest version of ledger-autosync (gitlab.com/egh/ledger-autosync) uses some unreleased features in ofxparse (namely, https://github.com/jseutter/ofxparse/pull/85) for improved support of investment transactions.

It would be great if their could be a new version of ofxparse released so that users installing ledger-autosync via pip or as a debian/ubuntu package could use this feature.

Thanks for all your work on this project.

**Comment by jaraco** [comment]
+1

**Comment by egh** [comment]
Any chance of a release? Thanks again!

**Comment by jseutter** [comment]
Yes, I just made a new release this week.  Sorry about the delay!

**Comment by egh** [comment]
Thank you!
